export const links = [
	/*{
		"image": "/src/lib/assets/test/2.jpg",
		"title": "TEST",
		"description": "TEST",
		"href": "https://pi.whoopradio.com",
		"category":["Main","Education","Assets","Reference","Documentation","GettingStarted",],
		"tags": ["Top","Test","Education","Math",],
		"price": "Free",
		"software": ["All",],
		"color": null,
		"score": null,
		// Color always overrides the price color
		// Color must always be a valid tailwindcss tag
		// See https://tailwindcss.com/docs/background-color
		"primaryTextColor": "text-[#00ff00]",
		"secondaryTextColor": "text-[#0000ff]",
	},*/
	//Main mixed files-------------------------------------------------------------------------------------------------------------------------------------

	{
		"image": "/src/lib/assets/1.jpg",
		"title": "3Dassets.one",
		"description": "A one stop shop for all of the internets best free cc0 assets all in one place!",
		"href": "https://www.3dassets.one/#order=latest",
		"category":["Main","Assets",],
		"tags": ["Top","AssetLibrary","Textures","Models",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/2.png",
		"title": "Physically Based Info",
		"description": "Scientifically documented information on materials + unit conversion to software",
		"href": "https://physicallybased.info/",
		"category":["Main","Education",],
		"tags": ["Top","Textures",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/3.png",
		"title": "Texture Ninja",
		"description": "cc0 Textures properly cropped and straightened for reference or use",
		"href": "https://texture.ninja/",
		"category":["Main","Reference","Assets",],
		"tags": ["AssetLibrary","Top","Textures",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/4.png",
		"title": "Unsplash",
		"description": "Database of cc0 and Free images ",
		"href": "https://unsplash.com/",
		"category":["Main","Reference","Assets",],
		"tags": ["AssetLibrary","Top","Textures",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/5.png",
		"title": "Glenn Meling",
		"description": "Thousands of useful Photoshop assets",
		"href": "https://www.glennmeling.com/photo-and-photoshop",
		"category":["Assets",],
		"tags": ["AssetLibrary","Top","Textures",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
		{
		"image": "/src/lib/assets/AdobieFonts.jpg",
		"title": "Adobe Fonts",
		"description": "Paid but Excelent",
		"href": "https://fonts.adobe.com/",
		"category":["Main","Assets",],
		"tags": ["AssetLibrary","Top","Fonts",],
		"price": "Subscription",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/6.png",
		"title": "Online-Fonts",
		"description": "cc0 fonts https://fontsinuse.com/",
		"href": "https://online-fonts.com/",
		"category":["Main","Assets",],
		"tags": ["AssetLibrary","Top","Fonts",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/FontsInUse.jpg",
		"title": "Fonts In Use",
		"description": "An independent archive of typography",
		"href": "https://fontsinuse.com/",
		"category":["Main","Reference",],
		"tags": ["AssetLibrary","Top","Fonts",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/7.png",
		"title": "CG Cinematography",
		"description": "Everything you want to know about CG Cinematography and Lighting",
		"href": "https://chrisbrejon.com/cg-cinematography/",
		"category":["Main","Education",],
		"tags": ["Top","Lighting",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/8.png",
		"title": "The Level Design Book",
		"description": "An approachable, up-to-date, and critical reference on Level Design.",
		"href": "https://book.leveldesignbook.com/",
		"category":["Education",],
		"tags": ["LevelDesign","Top",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/9.png",
		"title": "Inigo Quiilez",
		"description": "A Pixar artist teaches all you need to know about shaders",
		"href": "https://iquilezles.org/",
		"category":["Main","Education",],
		"tags": ["Top","Shaders","Rendering",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/10.png",
		"title": "Evan E. Richards",
		"description": "A free library of final movie frames",
		"href": "https://www.evanerichards.com/index",
		"category":["Main","Reference",],
		"tags": ["Top",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/11.png",
		"title": "George Zaky",
		"description": "Character Anatomy Perfected",
		"href": "https://georgezaky108.artstation.com/",
		"category":["Main","Education","Reference",],
		"tags": ["ModelingCharacters","Anatomy",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/12.png",
		"title": "Z Anatomy",
		"description": "Open source 3D atlas of anatomy",
		"href": "https://lluisv.itch.io/z-anatomy",
		"category":["Main","Education","Reference",],
		"tags": ["ModelingCharacters","Anatomy",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/13.png",
		"title": "Anatomy for sculptors",
		"description": "Anatomy books for artists. Website: anatomy4sculptors.com",
		"href": "https://www.artstation.com/anatomy4sculptors",
		"category":["Main","Education","Reference",],
		"tags": ["ModelingCharacters","Anatomy",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/14.png",
		"title": "Nasa Visible Earth",
		"description": "A catalog of NASA images and animations of our home planet",
		"href": "https://visibleearth.nasa.gov/",
		"category":["Main","Reference",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/15.png",
		"title": "OpenStreetMap",
		"description": "cc0 street data: blender plugin: https://github.com/vvoovv/blosm",
		"href": "https://www.openstreetmap.org/#map=16/30.6140/-96.3448",
		"category":["Assets",],
		"tags": ["Tools",],
		"software": ["Blender",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/16.png",
		"title": "Living Lines Library",
		"description": "The best collection of production art on the internet.",
		"href": "https://livlily.blogspot.com/2010/11/model-sheets-production-drawings.html",
		"category":["Main","Education","Reference",],
		"tags": ["Animation","CharacterDesign",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/17.png",
		"title": "Art Of Animation",
		"description": "Character Design References",
		"href": "https://characterdesignreferences.com/art-of-animation",
		"category":["Main","Education","Reference",],
		"tags": ["Animation","CharacterDesign",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/18.png",
		"title": "Blender Guru",
		"description": "Where to start with blender, by the founder of polygon.",
		"href": "https://www.blenderguru.com/",
		"category":["Education",],
		"tags": ["Tutorials",],
		"software": ["Blender",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/Wikipedia2.jpg",
		"title": "Wikipedia",
		"description": "A free online encyclopedia, created and edited by volunteers around the world and hosted by the Wikimedia Foundation.",
		"href": "https://www.wikipedia.org/",
		"category":["Main","Reference",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/Artstation.jpg",
		"title": "ArtStation",
		"description": "the leading showcase platform for games, film, media & entertainment artists.",
		"href": "https://www.artstation.com/?sort_by=community&dimension=all",
		"category":["Main","Education","GettingStarted",],
		"tags": ["Breakdowns","Tutorials",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/ArtstationLearning.jpg",
		"title": "ArtStation/Learning",
		"description": "an excelent resource for learning.",
		"href": "https://www.artstation.com/learning",
		"category":["Education",],
		"tags": ["Courses",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	{
		"image": "/src/lib/assets/Lomography.jpg",
		"title": "Lomography",
		"description": "Film photography, searchable by camera, lens, film stock and more.",
		"href": "https://www.lomography.com/",
		"category":["Main","Reference",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	//Education-------------------------------------------------------------------------------------------------------------------------------------
	{
		"image": "/src/lib/assets/spectralmaterials.jpg",
		"title": "Spectral Materials Database",
		"description": "1,294 measurements of opaque materials recorded using various spectrally-specific spectrophotmeter sensing devices",
		"href": "https://spectraldb.com/",
		"category":["Education",],
		"tags": ["Top","Textures",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/VFXDoc.jpg",
		"title": "VFX Doc",
		"description": "Realtime VFX Documentation for visual effect artist and tech art field for real-time graphics and games. ",
		"href": "https://vfxdoc.readthedocs.io/en/latest/",
		"category":["Education",],
		"tags": ["Top",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/UnityLibrary.jpg",
		"title": "The Unity Library",
		"description": "A collection of resources for Unity Game Development and Game Techniques.",
		"href": "https://unity.stelabouras.com/",
		"category":["Education",],
		"tags": ["Top",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/theGraphicsCodex.jpg",
		"title": "The Graphics Codex",
		"description": "The essential digital reference and learning resource for computer graphics.",
		"href": "https://graphicscodex.com/",
		"category":["Education",],
		"tags": ["Math",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/CGPrinciplesAndPractice.jpg",
		"title": "CG PrinciplesPractice",
		"description": "The principles, as well as the mathematics, underlying computer graphics--knowledge that is essential for successful work both now and in the future.",
		"href": "https://casual-effects.com/cgpp/about.xml",
		"category":["Education",],
		"tags": ["Shaders","Rendering",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/ImmersiveLinearAlgebra.jpg",
		"title": "Immersive Linear Algebra",
		"description": "The world's first linear algebra book with fully interactive figures.",
		"href": "https://immersivemath.com/ila/index.html",
		"category":["Education",],
		"tags": ["Math",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/math2.jpg",
		"title": "math2.org",
		"description": "Math Reference Tables useful to Shaders and Artist.",
		"href": "http://math2.org/",
		"category":["Education",],
		"tags": ["Math",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/faceBlendshapes.jpg",
		"title": "arkit Blendshapes",
		"description": "Examples of each blendshape for mocap .",
		"href": "https://arkit-face-blendshapes.com/",
		"category":["Education",],
		"tags": ["ModelingCharacters",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/FlippedNormals.jpg",
		"title": "FlipppedNormals",
		"description": "YouTube Character Masterclass",
		"href": "https://www.youtube.com/@fnmarket/videos",
		"category":["Education",],
		"tags": ["ModelingCharacters",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/IntoAnimation.jpg",
		"title": "Into Animation",
		"description": "A true Animation Masterclass",
		"href": "https://www.intoanimation.com/",
		"category":["Education",],
		"tags": ["ModelingCharacters","Animation",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/AlejandroGarcia.jpg",
		"title": "Alejandro Garcia",
		"description": "The Physics of Animation",
		"href": "https://www.youtube.com/c/AlejandroLuisGarcia",
		"category":["Education",],
		"tags": ["Animation",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/AaronBlaise.jpg",
		"title": "Aaron Blaise",
		"description": "2D Animation, Taught by one of Disney's Best, Director of Brother Bear",
		"href": "https://www.youtube.com/@AaronBlaiseArt/videos",
		"category":["Education",],
		"tags": ["Animation",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/BigMediumSmall.jpg",
		"title": "Big Medium Small",
		"description": "The idea that design shapes should follow a basic hierarchy of size and adhere to specific ratios.",
		"href": "https://www.youtube.com/watch?v=ZluGXgpdJj4",
		"category":["Education",],
		"tags": ["ModelingHardSurface",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/StylizedEnvironment.jpg",
		"title": "Stylized Environment",
		"description": "Using Substance and Blender to make a Stylized UE5 Environment.",
		"href": "https://80.lv/articles/using-blender-substance-3d-designer-to-make-a-stylized-diorama-in-unreal-engine-5/",
		"category":["Education",],
		"tags": ["Environment",],
		"software": ["Blender","Unreal","Substance",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/ModularKits.jpg",
		"title": "Modular Env. Kits",
		"description": "Modular Kits for Game Environments w/ Jon Arellano, artist at Sony Santa Monica.",
		"href": "https://www.youtube.com/watch?v=77xPHfzciiY",
		"category":["Education",],
		"tags": ["Environment","ModelingHardSurface"],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/KönigsbergCastle.jpg",
		"title": "Königsberg Castle",
		"description": "One of the Finest Stylized Scene breakdowns.",
		"href": "https://www.artstation.com/artwork/yDPXJ5",
		"category":["Education",],
		"tags": ["Environment","ModelingHardSurface",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/StylizedCharacterWorkflow.jpg",
		"title": "Stylized Character Workflow",
		"description": "How to Create a Stylized Character, Start to finish.",
		"href": "https://www.artstation.com/artwork/yDPXJ5",
		"category":["Education",],
		"tags": ["ModelingCharacters",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/EagleSummitWagon.jpg",
		"title": "Eagle Summit Wagon",
		"description": "The Best modeled car I have Ever Seen.",
		"href": "https://www.artstation.com/artwork/zPwlwm",
		"category":["Education",],
		"tags": ["ModelingHardSurface",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/CharacterSimulation.jpg",
		"title": "Character Simulation",
		"description": "The Pipeline of Character Simulation.",
		"href": "https://www.artstation.com/artwork/39b6zY",
		"category":["Education",],
		"tags": ["Animation","ModelingCharacters",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/modelingBuildings.jpg",
		"title": "Modeling Buildings",
		"description": "how to model vfx style buidlings",
		"href": "https://www.youtube.com/watch?v=Jhc0dzImJI8",
		"category":["Education",],
		"tags": ["ModelingHardSurface",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/JulienHerbey.jpg",
		"title": "Julien Herbey",
		"description": "Breakdowns from an ILM Generalist that prove software is not the reason your scenes look poor.",
		"href": "https://www.artstation.com/juvfx",
		"category":["Education",],
		"tags": ["Environment","Compositing","ModelingHardSurface",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/PabloDominguez.jpg",
		"title": "Pablo Dominguez",
		"description": "Breakdowns from another ILM Generalist that prove software is not the reason your scenes look poor.",
		"href": "https://www.artstation.com/pablodominguez",
		"category":["Education",],
		"tags": ["Environment","Compositing","ModelingHardSurface",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/MateuszKozica.jpg",
		"title": "Mateusz Kozica",
		"description": "How to build a Level, from a pro.",
		"href": "https://www.artstation.com/mateuszkozica",
		"category":["Education",],
		"tags": ["Environment","LevelDesign","Shaders","ModelingHardSurface",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/PaulChadeisson.jpg",
		"title": "Paul Chadeisson",
		"description": "Another Amazing artist who proves software or hardware isn't what matters.",
		"href": "https://www.artstation.com/pao",
		"category":["Education",],
		"tags": ["Environment","Compositing","ModelingHardSurface",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/FalkBoje.jpg",
		"title": "Falk Boje",
		"description": "ILM Style Scenes with tutorials",
		"href": "https://www.artstation.com/falkboje",
		"category":["Education",],
		"tags": ["Environment","Compositing","ModelingHardSurface",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/JamaJurabaev.jpg",
		"title": "Jama Jurabaev",
		"description": "How to Create Environments from an ILM artist",
		"href": "https://jamajurabaev.gumroad.com/l/Lstpj",
		"category":["Education",],
		"tags": ["Environment","Compositing","ModelingHardSurface",],
		"price": "OneTimePurchase",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/Curvenet.jpg",
		"title": "Curvenet Deformer",
		"description": "What is Curvenet? A Pixar Inovation In Animation",
		"href": "https://www.youtube.com/watch?v=HnYlTPucxRc",
		"category":["Education",],
		"tags": ["Rigging",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	//Reference-------------------------------------------------------------------------------------------------------------------------------------
	{
		"image": "/src/lib/assets/CharacterDesignReferences.jpg",
		"title": "Character Design References",
		"description": "A collection of Art of and Artist Portfolios.",
		"href": "https://characterdesignreferences.com/",
		"category":["Reference",],
		"tags": ["CharacterDesign",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/WalkCycleDepot.jpg",
		"title": "Walk Cycle Depot",
		"description": "A collection of traditional 2D Walk Cycles.",
		"href": "https://walk-cycle-depot.blogspot.com/",
		"category":["Education","Reference",],
		"tags": ["Animation",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/AnimationResources.jpg",
		"title": "AnimationResources",
		"description": "A collection of articles on Animation.",
		"href": "https://animationresources.org/",
		"category":["Education","Reference",],
		"tags": ["Animation",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/80lv.jpg",
		"title": "80.lv",
		"description": "A collection of articles on Animation.",
		"href": "https://80.lv/articles/",
		"category":["Main","Education",],
		"tags": ["Breakdowns","Tutorials",],
		"price": "Free",
		"color": null,
		"score": 100,
	},
	
	//Documentation-------------------------------------------------------------------------------------------------------------------------------------
	{
		"image": "/src/lib/assets/doc_blenderref.jpg",
		"title": "Blender Reference Manual",
		"description": "Welcome to the manual for Blender",
		"href": "https://docs.blender.org/manual/en/latest/",
		"category":["Documentation",],
		"tags": [],
		"software": ["Blender",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/doc_blenderapi.jpg",
		"title": "Blender 4.3 Python API Documentation",
		"description": "Python API documentation for Blender",
		"href": "https://docs.blender.org/api/current/index.html",
		"category":["Documentation",],
		"tags": [],
		"software": ["Blender",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/doc_blenderdev.jpg",
		"title": "Blender Developer Documentation",
		"description": "Build blender yourself, for new and experienced developers alike.",
		"href": "https://developer.blender.org/docs/",
		"category":["Documentation",],
		"tags": [],
		"software": ["Blender",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/doc_unreal.jpg",
		"title": "Unreal 5.5 Documentaion",
		"description": "Complete resources for learning to use Unreal Engine 5",
		"href": "https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-5-5-documentation",
		"category":["Documentation",],
		"tags": ["GameDevelopment",],
		"software": ["Unreal",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/doc_unrealpythonapi.jpg",
		"title": "Unreal 5.5 Python API",
		"description": "Python API documentation for Unreal, change the version number in the url",
		"href": "https://dev.epicgames.com/documentation/en-us/unreal-engine/python-api/?application_version=5.5",
		"category":["Documentation",],
		"tags": ["GameDevelopment",],
		"software": ["Unreal",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/doc_unrealcplusplusapi.jpg",
		"title": "Unreal 5.5 C++ API",
		"description": "C++ API documentation for Unreal, work in progress",
		"href": "https://dev.epicgames.com/documentation/en-us/unreal-engine/API",
		"category":["Documentation",],
		"tags": ["GameDevelopment",],
		"software": ["Unreal",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/doc_unrealdevcom.jpg",
		"title": "Unreal Dev Community",
		"description": "Courses on how to learn game development / Unreal",
		"href": "https://dev.epicgames.com/community/",
		"category":["Documentation",],
		"tags": ["GameDevelopment",],
		"software": ["Unreal",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/doc_unitymanual.jpg",
		"title": "Unity User Manual",
		"description": "Unity Engine User Manual",
		"href": "https://docs.unity3d.com/Manual/index.html",
		"category":["Documentation",],
		"tags": ["GameDevelopment",],
		"software": ["Unity",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/doc_unityapi.jpg",
		"title": "Unity Scritping Ref",
		"description": "Scripting API for Unity C#",
		"href": "https://docs.unity3d.com/ScriptReference/index.html",
		"category":["Documentation",],
		"tags": ["GameDevelopment",],
		"software": ["Unity",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/doc_davinciresolvetraining.jpg",
		"title": "Davinci Resolve Training",
		"description": "Introduction to using Davinci Resolve",
		"href": "https://www.blackmagicdesign.com/products/davinciresolve/training",
		"category":["Documentation",],
		"tags": [],
		"software": ["Davinciresolve",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/doc_davinciresolvemanual.jpg",
		"title": "Davinci Resolve Manual",
		"description": "4000+ pages, change the version number in the url",
		"href": "https://documents.blackmagicdesign.com/UserManuals/DaVinci_Resolve_19_Reference_Manual.pdf",
		"category":["Documentation",],
		"tags": [],
		"software": ["Davinciresolve",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/MDN_HTML.jpg",
		"title": "MDN HTML",
		"description": "coding for pros - html",
		"href": "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content",
		"category":["Documentation",],
		"tags": ["WebDevelopment",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/MDN_CSS.jpg",
		"title": "MDN CSS",
		"description": "coding for pros - CSS",
		"href": "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content",
		"category":["Documentation",],
		"tags": ["WebDevelopment",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/MDN_JavaScript2.jpg",
		"title": "MDN JavaScript",
		"description": "coding for pros - JavaScript",
		"href": "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content",
		"category":["Documentation",],
		"tags": ["WebDevelopment",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/doc_w3schoolscss.jpg",
		"title": "W3 schools",
		"description": "coding for noobs",
		"href": "https://www.w3schools.com/css/default.asp",
		"category":["Documentation",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/perforce.jpg",
		"title": "Perforce",
		"description": "Recomended soruce control for unreal dev",
		"href": "https://www.perforce.com/",
		"category":["Documentation",],
		"tags": [],
		"software": ["Unreal",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/unityversioncontrol.jpg",
		"title": "Unity Version Control",
		"description": "Recomended soruce control for Unity dev",
		"href": "https://unity.com/solutions/version-control",
		"category":["Documentation",],
		"tags": [],
		"software": ["Unity",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	//GettingStarted-------------------------------------------------------------------------------------------------------------------------------------
	{
		"image": "/src/lib/assets/blender.jpg",
		"title": "Blender",
		"description": "The best piece of software I have ever used. Period. Free Forever",
		"href": "https://www.blender.org/",
		"category":["GettingStarted",],
		"tags": [],
		"software": ["Blender",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/blenderextensions.jpg",
		"title": "Blender Extensions",
		"description": "The best Extension site I have ever used. Period.",
		"href": "https://extensions.blender.org/",
		"category":["GettingStarted",],
		"tags": [],
		"software": ["Blender",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/unreal.jpg",
		"title": "Unreal Engine",
		"description": "Another of the best piece of software I have ever used. Period. Fairly Priced",
		"href": "https://www.unrealengine.com/en-US",
		"category":["GettingStarted",],
		"tags": [],
		"software": ["Unreal",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/storyboarder.jpg",
		"title": "Storyboarder",
		"description": "Open source, excelently integrated, Story boarding tool",
		"href": "https://wonderunit.com/storyboarder/index.html",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/drawio.jpg",
		"title": "draw.io",
		"description": "free sketching and diagramming functionality",
		"href": "https://www.drawio.com/",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/krita.jpg",
		"title": "KRITA",
		"description": "Krita is a professional FREE and open source painting program.",
		"href": "https://krita.org/en/",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/clipstudio.jpg",
		"title": "Clip Studio Paint",
		"description": "The popular alternative: with asset store",
		"href": "https://www.clipstudio.net/en/",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/darktable.jpg",
		"title": "darktable",
		"description": "open source photography workflow application and raw developer",
		"href": "https://www.darktable.org/",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/pureref.jpg",
		"title": "PureRef",
		"description": "One of the most used tools: a stand-alone program for Windows, Mac and Linux that keeps track of your images.",
		"href": "https://www.pureref.com/",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/synchSketch.jpg",
		"title": "synchsketch",
		"description": "A visual Collaboration tool for easy Critique",
		"href": "https://syncsketch.com/",
		"category":["GettingStarted",],
		"tags": [],
		"software": ["All",],
		"price": ["Subscription","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/materialize.jpg",
		"title": "Materialize",
		"description": "a stand alone tool for creating materials for use in games from images. also see: https://github.com/BoundingBoxsoftware/Materialize  ",
		"href": "https://www.boundingboxsoftware.com/materialize/",
		"category":["GettingStarted","Assets",],
		"tags": ["Tools",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/winderstat.jpg",
		"title": "WinDirStat",
		"description": "A disk usage statistics viewer and cleanup assistant ",
		"href": "https://windirstat.net/",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/obs.jpg",
		"title": "OBS",
		"description": "Free and open source software for video recording and live streaming.",
		"href": "https://obsproject.com/",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/vlc2.jpg",
		"title": "VLC",
		"description": "a free and open source cross-platform multimedia player",
		"href": "https://www.videolan.org/vlc/",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/fspy.jpg",
		"title": "fSpy",
		"description": "open source still image camera matching",
		"href": "https://fspy.io/",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/kylebrushes.jpg",
		"title": "Kyle Brushes",
		"description": "all the brushes that should be default in photoshop but are not.",
		"href": "https://www.adobe.com/products/photoshop/brushes",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/studiolookdev.jpg",
		"title": "Studio Look Dev Scene",
		"description": "An industry standard look dev scene for all scales of objects.",
		"href": "https://www.cgtrader.com/free-3d-models/architectural/other/studio-lookdev",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/davinciresolve.jpg",
		"title": "Davinci Resolve",
		"description": "Professional Editing, Color, Effects and Audio Post!",
		"href": "https://www.blackmagicdesign.com/products/davinciresolve",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/fountain.jpg",
		"title": "Fountain",
		"description": "free and open-source screenplay writing",
		"href": "https://fountain.io/",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/vizlab2.jpg",
		"title": "Vizlab.org/assets",
		"description": "Here is where to find a bunch of CC0 (that means free)",
		"href": "https://vizlab.org/assets",
		"category":["GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/gaea.jpg",
		"title": "Gaea",
		"description": "Industry standard terrain generation",
		"href": "https://quadspinner.com/",
		"category":["GettingStarted",],
		"tags": [],
		"price": "OneTimePurchase",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/substance.jpg",
		"title": "Substance Painter",
		"description": "Recomended one time purchase from steam.",
		"href": "https://store.steampowered.com/search/?developer=Adobe",
		"category":["GettingStarted",],
		"tags": [],
		"price": "OneTimePurchase",
		"color": null,
		"score": null,
	},
		{
		"image": "/src/lib/assets/git.jpg",
		"title": "git",
		"description": "Recomended source control for solor game dev",
		"href": "https://git-scm.com/",
		"category":["Documentation","GettingStarted",],
		"tags": [],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/perforce.jpg",
		"title": "Perforce",
		"description": "Recomended soruce control for unreal dev",
		"href": "https://www.perforce.com/",
		"category":["GettingStarted",],
		"tags": [],
		"software": ["Unreal",],
		"price": ["Subscription","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/unityversioncontrol.jpg",
		"title": "Unity Version Control",
		"description": "Recomended soruce control for Unity dev",
		"href": "https://unity.com/solutions/version-control",
		"category":["GettingStarted",],
		"tags": [],
		"price": ["Subscription","Free",],
		"color": null,
		"score": null,
	},
	
	//Assets-----------------------------------------------------------------------------------------------------------------------------------------
	{
		"image": "/src/lib/assets/Textures.jpg",
		"title": "Textures.com",
		"description": "Free and Premium High Quility Assets",
		"href": "https://www.textures.com/library",
		"category":["Assets",],
		"tags": ["AssetLibrary","Textures","Models",],
		"price": ["Subscription","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/PolyHaven.jpg",
		"title": "Poly Haven",
		"description": "The Public 3D Asset Library / https://github.com/Poly-Haven",
		"href": "https://polyhaven.com/",
		"category":["Assets",],
		"tags": ["AssetLibrary","Plugin","Textures","Models",],
		"software": ["Blender",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/QuixelMegascans.jpg",
		"title": "Quixel Megascans",
		"description": "3D Asset and Texture Library, dont forget to use QuixelBridge",
		"href": "https://quixel.com/megascans/home",
		"category":["Assets",],
		"tags": ["AssetLibrary","Plugin","Textures","Models",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/fab.jpg",
		"title": "FAB",
		"description": "The biggest 3D Asset and Texture Marketplace.",
		"href": "https://www.fab.com/",
		"category":["Assets",],
		"tags": ["AssetLibrary","Plugin","Textures","Models",],
		"price": "OneTimePurchase",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/Poliigon.jpg",
		"title": "Poliigon",
		"description": "The biggest 3D Asset and Texture library. Substantial Free Section",
		"href": "https://www.poliigon.com/",
		"category":["Assets",],
		"tags": ["AssetLibrary","Plugin","Textures","Models",],
		"price": ["Subscription","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/artstationdevtools.jpg",
		"title": "Artstation - Dev Tools",
		"description": "MUCH IS FREE! 2782 Dev Tools Resources.",
		"href": "https://www.artstation.com/marketplace/game-dev/resources/dev-tools",
		"category":["Assets",],
		"tags": ["AssetLibrary","Textures","Models","Plugin",],
		"software": ["Maya",],
		"price": ["OneTimePurchase","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/rawcatalog.jpg",
		"title": "RAW Catalog",
		"description": "A large 3D Asset and Texture library.",
		"href": "https://rawcatalog.com/library/",
		"category":["Assets",],
		"tags": ["AssetLibrary","Textures","Models",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/thebasemesh.jpg",
		"title": "The Base Mesh",
		"description": "Clean Topology, UV Unwrapped, Real world Scale Asset Library.",
		"href": "https://www.thebasemesh.com/",
		"category":["Assets",],
		"tags": ["AssetLibrary","Models",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/sharetextures.jpg",
		"title": "sharetextures",
		"description": "A large CC0 3D Asset, Atlass, and Texture library.",
		"href": "https://www.sharetextures.com/",
		"category":["Assets",],
		"tags": ["AssetLibrary","Textures","Models",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/cgbookcase.jpg",
		"title": "cgbookcase",
		"description": "A large CC0 Texture library.",
		"href": "https://www.cgbookcase.com/textures",
		"category":["Assets",],
		"tags": ["AssetLibrary","Textures",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/texturebox.jpg",
		"title": "Texture Box",
		"description": "A Texture library. Limited numer of downloads a day.",
		"href": "https://texturebox.com/free",
		"category":["Assets",],
		"tags": ["AssetLibrary","Textures",],
		"price": ["Subscription","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/blendermarket.jpg",
		"title": "Blender Market",
		"description": "MUCH IS FREE! 61,362 hand-crafted, high quality Blender models, shaders, add-ons and more from independent creators.",
		"href": "https://blendermarket.com/",
		"category":["Assets",],
		"tags": ["AssetLibrary","Textures","Models","Plugin",],
		"software": ["Blender",],
		"price": ["OneTimePurchase","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/gumroadblender.jpg",
		"title": "Gumroad - Blender",
		"description": "MUCH IS FREE! 8492 hand-crafted, high quality Blender models, shaders, add-ons and more from independent creators.",
		"href": "https://gumroad.com/3d?tags=blender",
		"category":["Assets",],
		"tags": ["AssetLibrary","Textures","Models","Plugin",],
		"software": ["Blender",],
		"price": ["OneTimePurchase","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/gumroadmaya.jpg",
		"title": "Gumroad - Maya",
		"description": "MUCH IS FREE! 1064 hand-crafted, high quality Maya models, shaders, add-ons and more from independent creators.",
		"href": "https://gumroad.com/3d?query=maya&tags=maya",
		"category":["Assets",],
		"tags": ["AssetLibrary","Textures","Models","Plugin",],
		"software": ["Maya",],
		"price": ["OneTimePurchase","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/artstationblender.jpg",
		"title": "Artstation - Blender",
		"description": "MUCH IS FREE! 162 Dev Tools Resources.",
		"href": "https://www.artstation.com/marketplace/game-dev/resources/dev-tools/scripts?section=trending&softwares=blender",
		"category":["Assets",],
		"tags": ["AssetLibrary","Textures","Models","Plugin",],
		"software": ["Blender",],
		"price": ["OneTimePurchase","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/artstationmaya.jpg",
		"title": "Artstation - Maya",
		"description": "MUCH IS FREE! 246 Dev Tools Resources.",
		"href": "https://www.artstation.com/marketplace/game-dev/resources/dev-tools/scripts?section=trending&softwares=maya",
		"category":["Assets",],
		"tags": ["AssetLibrary","Textures","Models","Plugin",],
		"software": ["Maya",],
		"price": ["OneTimePurchase","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/animationmethods.jpg",
		"title": "Animation Methods - Maya",
		"description": "Many Free: Incredibly usefull tools for the Maya Artist",
		"href": "https://animationmethods.com/tools.html",
		"category":["Assets",],
		"tags": ["AssetLibrary","Plugin",],
		"software": ["Maya",],
		"price": ["OneTimePurchase","Free",],
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/autodeskarea.jpg",
		"title": "Autodesk Area - Maya",
		"description": "some dev tools for Maya Artist",
		"href": "https://area.autodesk.com/learn/assets/?page=1&order=recent&tools=13",
		"category":["Assets",],
		"tags": ["AssetLibrary","Plugin",],
		"software": ["Maya",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	//Assets-blenderbest----------------------------------------------------------------------------------------------------------------------------------------
	//Assets-plants----------------------------------------------------------------------------------------------------------------------------------------
	{
		"image": "/src/lib/assets/GlobePlants.jpg",
		"title": "Globe Plants",
		"description": "A Premium PBR Plant Library",
		"href": "https://globeplants.com/collections",
		"category":["Assets",],
		"tags": ["AssetLibrary","Plants",],
		"price": "OneTimePurchase",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/grasswald.jpg",
		"title": "Graswalld + gscatter",
		"description": "Blender scattering and grass made easy",
		"href": "https://store.gscatter.com/assets",
		"category":["Assets",],
		"tags": ["AssetLibrary","Plants","Plugin","Tools",],
		"software": ["Blender",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/Maxtree.jpg",
		"title": "Maxtree",
		"description": "PBR Plants for purchase, includes a free pack",
		"href": "https://maxtree.org/product-category/collection/",
		"category":["Assets",],
		"tags": ["AssetLibrary","Plants",],
		"price": "OneTimePurchase",
		"color": null,
		"score": null,
	},
	//Assets-misc----------------------------------------------------------------------------------------------------------------------------------------
	{
		"image": "/src/lib/assets/IESLibrary.jpg",
		"title": "IES Library",
		"description": "917'996 IES-files available with preview",
		"href": "https://ieslibrary.com/",
		"category":["Assets",],
		"tags": ["AssetLibrary",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/dafont.jpg",
		"title": "dafont",
		"description": "92,876 fonts",
		"href": "https://www.dafont.com/",
		"category":["Assets",],
		"tags": ["AssetLibrary",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/audiolibrary.jpg",
		"title": "YouTube Audio Library",
		"description": "free cc0 music and Sound Effects",
		"href": "https://www.youtube.com/audiolibrary",
		"category":["Assets",],
		"tags": ["AssetLibrary",],
		"price": "Free",
		"color": null,
		"score": null,
	},
	{
		"image": "/src/lib/assets/bigprint.jpg",
		"title": "BigPrint",
		"description": "Make large scale-accurate 1:1 print mosaics from images",
		"href": "https://woodgears.ca/bigprint/",
		"category":["Assets",],
		"tags": ["Tools",],
		"price": "OneTimePurchase",
		"color": null,
		"score": null,
	},
	//SomethingMissing?---- Should always be last in list here-------------------------------------------------------------------------------------------------------------------------------------
	{
		"image": "/src/lib/assets/question_background.png",
		"title": "Missing Something?",
		"description": "Request it to be added by filling out this form",
		"href": "https://forms.gle/c1YCDTgXBYcnF2oS6",
		"category":["Main","Education","Assets","Reference","Documentation","GettingStarted",],
		"tags": ["Question",],
		"subtags": [],
		"software": ["All",],
		"price": ["Free", "Subscription", "OneTimePurchase"],
		//"color": "bg-[#11635a]",
		"score": 100,
		// Color always overrides the price color
		// Color must always be a valid tailwindcss tag
		// See https://tailwindcss.com/docs/background-color
		"primaryTextColor": "text-[#3098ff]",
		//"secondaryTextColor": "text-[#0000ff]",
	},
]